### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by BlazTrampus** [pauls-3d-things/blender-stl-render-scene#1]
when im load everything in blender and click run script i get an error.

`Traceback (most recent call last):
  File "/home/grid/Documents/blender-stl-render-scene-master/render-20x20.blend/render-pipeline.py", line 28, in <module>
  File "/home/grid/Documents/blender-stl-render-scene-master/render-20x20.blend/render-pipeline.py", line 19, in prepareObject
Exception: Material not found!
Error: Python script failed, check the message in the system console
`

is there anything that im doing wrong or is it the script itself?

**Comment by uvwxy** [comment]
Please pull my latest updates. The 20x20 was missing the reference to the render material.

**Comment by BlazTrampus** [comment]
that fixed the previous issue. now it outputs the single renders but when it tries to combine them i get the next errors.


`Traceback (most recent call last):
  File "/home/grid/Downloads/blender-stl-render-scene-master/render-20x20.blend/render-pipeline.py", line 54, in <module>
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 546, in truetype
    return freetype(font)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 543, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 161, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
Error: Python script failed, check the message in the system console
`

**Comment by uvwxy** [comment]
Unfortunately, you need to run Blender from within this repositories folder for it to work with the relative path to the font embedded into this project.
